name: Tests                          # name of the workflow (can be anything)

on:
  - push

jobs:
    test:
        runs-on: ubuntu-latest       # virtual machine (VM) to run the tests on

        steps:
        - uses: actions/checkout@v6  # download the code from the repository to the VM

        - name: Setup Python         # installs and configures Python runtime on the CI runner
          uses: actions/setup-python@v6
          with:
            python-version: '3.13'

        - name: Install dependencies 
          run: |
            python -m pip install --upgrade pip
            pip install pytest-playwright      

        - name: Ensure browser are installed
          run: python -m playwright install chromium --with-deps   # with all required system dependencies (Linux packages, libraries, fonts)
          
        - name: Run tests
          env:  ё1243ы Б
            GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
            GITHUB_USER: ${{ secrets.GITHUB_USER }}
            GITHUB_REPO: ${{ secrets.GITHUB_REPO }}
          run: pytest 